### ISSUE TITLE
(VBX 1.4.3) tutorials/mxnet/mobilefacenet-arcface: cannot download "model-y1.zip"

### ISSUE THREAD

**Issue by okawaj9** [Microchip-Vectorblox/VectorBlox-SDK#13]
VBX v1.4.3:

"tutorials/mxnet/mobilefacenet-arcface/mobilefacenet-arcface.sh" failed with executing "gdown 'https://drive.google.com/uc?id=1RHyJIeYuHduVDDBTn3ffpYEZoXWRamWI&authuser=0&export=download'" to download "model-y1.zip".

We would like to have a solution against below.   

[Error message]:

$ bash mobilefacenet-arcface.sh

Checking and Activating VBX Python Environment...
Downloading mobilefacenet-arcface...
Traceback (most recent call last):
  File "/home/okawa/Microchip/VBX/SDK/VectorBlox-SDK-release-v1.4.3/vbx_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/okawa/Microchip/VBX/SDK/VectorBlox-SDK-release-v1.4.3/vbx_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/okawa/Microchip/VBX/SDK/VectorBlox-SDK-release-v1.4.3/vbx_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/okawa/Microchip/VBX/SDK/VectorBlox-SDK-release-v1.4.3/vbx_env/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/okawa/Microchip/VBX/SDK/VectorBlox-SDK-release-v1.4.3/vbx_env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/okawa/Microchip/VBX/SDK/VectorBlox-SDK-release-v1.4.3/vbx_env/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
**ConnectionResetError: [Errno 104] Connection reset by peer**

Best Regards,
Okawa

**Comment by okawaj9** [comment]
"tutorials/onnx/genderage/genderage.sh" also failed with  gdown 'https://drive.google.com/uc?id=1Mm3TeUuaZOwmEMp0nGOddvgXCjpRodPU&authuser=0&export=download' to download "genderage.onnx". 
Could you please allow us to get pass the tutorial, please ?

Best Regards,
Okawa

**Comment by okawaj9** [comment]
Confirmed that this is network issue.  Once connecting to public network instead of company's network, this issue was gone.  Then close.  Many thanks.
