### ISSUE TITLE
Latest version fails to compile models

### ISSUE THREAD

**Issue by dhimiterq** [Microchip-Vectorblox/VectorBlox-SDK#15]
I'm testing the latest version on Ubuntu 20.04. When trying to compile a simple model from the Tensorflow2 directory

under VectorBlox-SDK/tutorials/tensorflow2/myfirstcnn and 
VectorBlox-SDK/tutorials/tensorflow2/myfirstcnn3 both fail with the following :

```
Generating VNNX for V1000 configuration...
Traceback (most recent call last):
  File "/home/dhq/VectorBlox-SDK/vbx_env/bin/generate_vnnx", line 33, in <module>
    sys.exit(load_entry_point('vbx', 'console_scripts', 'generate_vnnx')())
  File "/home/dhq/VectorBlox-SDK/vbx_env/bin/generate_vnnx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dhq/VectorBlox-SDK/python/vbx/vbx/generate/__init__.py", line 1, in <module>
    from .vnnx_flow import generate_vnnx
  File "/home/dhq/VectorBlox-SDK/python/vbx/vbx/generate/vnnx_flow.py", line 5, in <module>
    from . import onnx_convert
  File "/home/dhq/VectorBlox-SDK/python/vbx/vbx/generate/onnx_convert.py", line 12, in <module>
    from .onnx_infer import onnx_infer, onnx_activations_batched, onnx_random_infer, onnx_random_input, load_input
  File "/home/dhq/VectorBlox-SDK/python/vbx/vbx/generate/onnx_infer.py", line 8, in <module>
    from vbx.sim.model import Fletcher32
  File "/home/dhq/VectorBlox-SDK/python/vbx/vbx/sim/__init__.py", line 1, in <module>
    from .model import Model
  File "/home/dhq/VectorBlox-SDK/python/vbx/vbx/sim/model.py", line 1, in <module>
    from . import c as c_shim
  File "/home/dhq/VectorBlox-SDK/python/vbx/vbx/sim/c.py", line 8, in <module>
    _so = np.ctypeslib.load_library('libvbx_cnn_sim.so', os.path.dirname(__file__))
  File "/home/dhq/VectorBlox-SDK/vbx_env/lib/python3.8/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/usr/lib/python3.8/ctypes/__init__.py", line 448, in __getitem__
    return getattr(self, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/dhq/VectorBlox-SDK/python/vbx/vbx/sim/libvbx_cnn_sim.so: invalid ELF header
```

**Comment by dhimiterq** [comment]
When re-installing I get this error:

```
ERROR: /home/dhq/VectorBlox-SDK/python/third_party/openvino/model-optimizer is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
```

**Comment by dhimiterq** [comment]
downgraded and reinstalled again. There is still an error bu compilation of models goes through.

```
 Using cached sklearn-0.0.post7.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dhq/VectorBlox-SDK/vbx_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z_srx5i8/sklearn_16af60d77dd74a61966d3536d59282a3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z_srx5i8/sklearn_16af60d77dd74a61966d3536d59282a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6ikiqq5h
       cwd: /tmp/pip-install-z_srx5i8/sklearn_16af60d77dd74a61966d3536d59282a3/
  Complete output (18 lines):
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.

  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package

  If the previous advice does not cover your use case, feel free to report it at
  https://github.com/scikit-learn/sklearn-pypi-package/issues/new
  ----------------------------------------

```
