### ISSUE TITLE
generating VNNX failed when using YOLOV5 6.1 onnx model

### ISSUE THREAD

**Issue by zizimumu** [Microchip-Vectorblox/VectorBlox-SDK#17]
when generating YOLOV5 6.1 onnx model (https://github.com/ultralytics/yolov5/releases), generate_vnnx report "StridedSlice not implemented" error.

here is the bash script file:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
set -e
echo "Checking and Activating VBX Python Environment..."
if [ -z $VBX_SDK ]; then
    echo "\$VBX_SDK not set. Please run 'source setup_vars.sh' from the SDK's root folder" && exit 1
fi

echo "Running Model Optimizer..."

mo --input_model ../../../models/yolov5n.onnx \
--framework onnx \
--input_shape [1,3,640,640] \
--scale_values=[255.] \
--reverse_input_channels \
--static_shape

echo "Generating VNNX for V1000 configuration..."
generate_vnnx -x yolov5n.xml  -c V1000 -f ../../sample_images -o yolov5n.vnnx  --bias-correction

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

here is the log:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
vbx_env) emy@EMY:~/PolarFire/VectorBlox-SDK/tutorials/onnx/yolov5$ bash onnx_yolov5.sh
Checking and Activating VBX Python Environment...
Running Model Optimizer...
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /home/emy/PolarFire/VectorBlox-SDK/tutorials/onnx/yolov5/../../../models/yolov5n.onnx
        - Path for generated IR:        /home/emy/PolarFire/VectorBlox-SDK/tutorials/onnx/yolov5/.
        - IR output name:       yolov5n
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,3,640,640]
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         [255.]
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       True
        - Enable IR generation for fixed input shape:   True
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
OpenVINO runtime found in:      /home/emy/PolarFire/VectorBlox-SDK/vbx_env/lib/python3.8/site-packages/openvino
OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
/home/emy/PolarFire/VectorBlox-SDK/vbx_env/lib/python3.8/site-packages/numpy/lib/function_base.py:792: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, order=order, subok=subok, copy=True)
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/emy/PolarFire/VectorBlox-SDK/tutorials/onnx/yolov5/yolov5n.xml
[ SUCCESS ] BIN file: /home/emy/PolarFire/VectorBlox-SDK/tutorials/onnx/yolov5/yolov5n.bin
[ SUCCESS ] Total execution time: 0.46 seconds.
[ SUCCESS ] Memory consumed: 93 MB.
It's been a while, check for a new version of Intel(R) Distribution of OpenVINO(TM) toolkit here https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html?cid=other&source=prod&campid=ww_2022_bu_IOTG_OpenVINO-2022-1&content=upg_all&medium=organic or on the GitHub*
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai
Generating VNNX for V1000 configuration...
Traceback (most recent call last):
  File "/home/emy/PolarFire/VectorBlox-SDK/vbx_env/bin/generate_vnnx", line 33, in <module>
    sys.exit(load_entry_point('vbx', 'console_scripts', 'generate_vnnx')())
  File "/home/emy/PolarFire/VectorBlox-SDK/python/vbx/vbx/generate/__main__.py", line 20, in main
    generate_vnnx(args.xml,
  File "/home/emy/PolarFire/VectorBlox-SDK/python/vbx/vbx/generate/vnnx_flow.py", line 53, in generate_vnnx
    graph = onnx_convert.convert_openvino_xml_to_onnx(nodes, model_name, ir_version)
  File "/home/emy/PolarFire/VectorBlox-SDK/python/vbx/vbx/generate/onnx_convert.py", line 2375, in convert_openvino_xml_to_onnx
    nodes, inits, inputs, outputs = gen_onnx(vinodes)
  File "/home/emy/PolarFire/VectorBlox-SDK/python/vbx/vbx/generate/onnx_convert.py", line 2170, in gen_onnx
    raise NotImplementedError('{} not implemented'.format(vinode.type))
NotImplementedError: StridedSlice not implemented

**Comment by LianVictor** [comment]
For the error that you are seeing in which the Strided Slice isn't supported, the best way to address this issue is to do the following:

1. Train network
2. Export to onnx using Ultralytics "export" tool
3. Examine the onnx model using a tool like Netron
4. Find the names of the last convolution layers. Yolov5 models should have 3 outputs. See the image below for an example.
5. Make sure the names of the last conv layers are the same as in the model optimizer command line. 
 - IE: Modify the script to set outputs at the last convolution layers

```mo --input_model ultralytics.yolov5n.relu.onnx  
--framework onnx 
--input_shape [1,3,416,416] 
--scale_values=[255.] 
--reverse_input_channels 
--output=Conv_193,Conv_247,Conv_139 
--static_shape
```


![yolov5n_cut](https://github.com/Microchip-Vectorblox/VectorBlox-SDK/assets/141765299/4af92796-2b4e-40d6-8d26-1e175c345fdb)
